version: 2.1

jobs:
  publish:
    machine: true
    steps:
      - checkout
      - run:
          name: "Login docker hub"
          command: |
            echo "DOCKER_HUB_USER = $DOCKER_HUB_USER"
            docker login -u "$DOCKER_HUB_USER1" -p $DOCKER_HUB_TOKEN
      - run:
          name: "Setup custom environment variables"
          command: |
            echo "DOCKER_HUB_USER = $DOCKER_HUB_USER"
            echo 'export CI_PROJECT_DIR="$(pwd)"' >> $BASH_ENV
            echo 'export CI_IMAGE="$DOCKER_HUB_USER/node"' >> $BASH_ENV
            echo 'export CI_REGISTRY_IMAGE="docker.io/${CI_IMAGE}"' >> $BASH_ENV
      - run:
          name: "Run building scripts"
          command: |
            chmod +x -R $CI_PROJECT_DIR/scripts
            LATEST_VERSION=""
            while IFS= read -r line
            do
              $CI_PROJECT_DIR/scripts/custom-docker-build $line -t "$CI_REGISTRY_IMAGE:$line"
              LATEST_VERSION=$line
            done < "$CI_PROJECT_DIR/VERSIONS"
            if [ ! -z "$LATEST_VERSION" ]; then
              docker tag $CI_REGISTRY_IMAGE:$LATEST_VERSION $CI_REGISTRY_IMAGE:latest
              docker push $CI_REGISTRY_IMAGE:latest
            fi

workflows:
  build_and_test:
    jobs:
      - publish:
          filters:
            branches:
              only: setup-circle-ci
